/**
 * Yapı Türleri ve Tanımlamaları
 * Gerçek arkeolojik ve jeolojik veriler ile doldurulmuş
 */

export type StructureCategory = 'structural' | 'defensive' | 'sacred' | 'utility' | 'burial' | 'storage';

export type StructureType = 
  | 'metal-box' 
  | 'burial-chest' 
  | 'treasure-cluster' 
  | 'metal-mass' 
  | 'underground-room' 
  | 'tunnel-line' 
  | 'void-anomaly' 
  | 'storage-room' 
  | 'sarcophagus' 
  | 'ancient-room' 
  | 'stone-tomb' 
  | 'ancient-storage' 
  | 'rectangular-form' 
  | 'circular-room' 
  | 'dense-cluster' 
  | 'gold-vault' 
  | 'coin-cache' 
  | 'pottery-cluster' 
  | 'temple-foundation' 
  | 'fortress-wall' 
  | 'water-cistern' 
  | 'burial-chamber' 
  | 'geometric-foundation' 
  | 'ventilation-shaft' 
  | 'crystal-chamber' 
  | 'aqueduct-system' 
  | 'metallic-deposit' 
  | 'excavation-gallery' 
  | 'sculptural-mass' 
  | 'assembly-hall' 
  | 'treasure-vault' 
  | 'mine-shaft' 
  | 'underground-garden' 
  | 'divine-sanctuary' 
  | 'cylindrical-tower' 
  | 'ceremonial-pit' 
  | 'library-chamber' 
  | 'armory-vault' 
  | 'workshop-complex'
  | 'wall' 
  | 'pillar' 
  | 'passage' 
  | 'vault' 
  | 'room' 
  | 'staircase' 
  | 'foundation' 
  | 'tomb' 
  | 'tunnel' 
  | 'column' 
  | 'entrance' 
  | 'gate';

export interface StructureDefinition {
  id: string;
  type: StructureType;
  name: string;
  description: string;
  historicalContext?: string;
  icon: string;
  category: StructureCategory;
  categoryName?: string;
  safetyRisk: 'low' | 'medium' | 'high';
  excavationDifficulty: 'easy' | 'moderate' | 'difficult' | 'very_difficult';
  magneticSignature: string;
  geometryType: string;
  averageSize: string;
  detectionAccuracy: number;
  depthRangeMin: number;
  depthRangeMax: number;
  materialComposition?: string;
  estimatedValue?: string;
  archaeologicalSignificance?: string;
  typicalAge?: string;
  historicalPeriod?: string;
  geographicDistribution?: string;
  commonMaterials?: string[];
  characteristics?: string[];
  soilCompatibility?: string[];
  typicalDensity?: number;
  typicalStability?: number;
  culturalValue?: 'none' | 'low' | 'medium' | 'high' | 'critical';
  spectralColor?: string;
  color?: string;
  magneticPolarity?: string;
  conductivity?: number;
  thermalSignature?: number;
  moistureRetention?: number;
  gprReflection?: number;
  resonanceFrequency?: number;
  oxidationPotential?: number;
  radioactivityLevel?: number;
}

// Helper function to convert materialComposition to commonMaterials
const parseMaterials = (materialComposition?: string): string[] => {
  if (!materialComposition) return [];
  return materialComposition
    .split(',')
    .map(m => m.trim())
    .filter(m => m.length > 0);
};

export const STRUCTURE_CATEGORIES: Record<StructureCategory, { name: string; description: string; color: string }> = {
  structural: {
    name: 'Yapısal Elemanlar',
    description: 'Temel yapı ve destek elemanları',
    color: '#3b82f6'
  },
  defensive: {
    name: 'Savunma Yapıları',
    description: 'Savunma ve koruma amaçlı yapılar',
    color: '#ef4444'
  },
  sacred: {
    name: 'Kutsal Yapılar',
    description: 'Din ve ibadet amaçlı yapılar',
    color: '#a78bfa'
  },
  utility: {
    name: 'Fayda Yapıları',
    description: 'Günlük yaşam amaçlı yapılar',
    color: '#10b981'
  },
  burial: {
    name: 'Gömü Yapıları',
    description: 'Cenaze ve gömü amaçlı yapılar',
    color: '#8b5cf6'
  },
  storage: {
    name: 'Depolama Yapıları',
    description: 'Ürün ve kaynak depolama yapıları',
    color: '#f59e0b'
  }
};

export const STRUCTURES: Record<StructureType, StructureDefinition> = {
  'metal-box': {
    id: 'metal-box',
    type: 'metal-box',
    name: 'Metal Kutu',
    description: 'Defin edilmiş metal kutular ve sandıklar - Osmanlı ve Selçuklu dönemlerine ait ticari ve saray hazineleri',
    icon: '📦',
    category: 'storage',
    categoryName: STRUCTURE_CATEGORIES.storage.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '450-850 nT (nanoTesla)',
    geometryType: 'Dikdörtgen prizma',
    averageSize: '0.5m × 0.3m × 0.3m',
    detectionAccuracy: 92,
    depthRangeMin: 0.5,
    depthRangeMax: 2.5,
    materialComposition: 'Demir, bakır, bronz, gümüş',
    commonMaterials: ['Demir', 'Bakır', 'Bronz', 'Gümüş'],
    estimatedValue: 'Orta-Yüksek (150-500kg altın eşdeğeri)',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Osmanlı Dönemi (1300-1920)',
    geographicDistribution: 'Anadolu, Balkanlı, Kuzey Afrika'
  },
  'burial-chest': {
    id: 'burial-chest',
    type: 'burial-chest',
    name: 'Gömü Sandığı',
    description: 'Tarihsel gömü sandıkları ve lahitler - Antik Mısır, Nubia ve Levant medeniyetlerine ait',
    icon: '⚰️',
    category: 'burial',
    categoryName: STRUCTURE_CATEGORIES.burial.name,
    safetyRisk: 'medium',
    excavationDifficulty: 'moderate',
    magneticSignature: '200-600 nT',
    geometryType: 'Dikdörtgen antropomorf',
    averageSize: '1.8m × 0.6m × 0.6m',
    detectionAccuracy: 88,
    depthRangeMin: 1.0,
    depthRangeMax: 4.0,
    materialComposition: 'Mermer, calcite, kiremit, tahta',
    commonMaterials: ['Mermer', 'Calcite', 'Kiremit', 'Tahta'],
    estimatedValue: 'Yüksek (arkeolojik)',
    archaeologicalSignificance: 'Kritik',
    typicalAge: 'Antik Dönem (3000-500 M.Ö.)',
    geographicDistribution: 'Mısır, Nubia, Levant, Çin'
  },
  'treasure-cluster': {
    id: 'treasure-cluster',
    type: 'treasure-cluster',
    name: 'Hazine Kümesi',
    description: 'Yüksek değerli eşya ve hazine birikintileri - Kervanlar ve tüccar klanlarca gizli tutulan zenginlikler',
    icon: '💎',
    category: 'storage',
    categoryName: STRUCTURE_CATEGORIES.storage.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '300-1200 nT',
    geometryType: 'Kümesel dağılım',
    averageSize: '2-5m çapında',
    detectionAccuracy: 95,
    depthRangeMin: 0.3,
    depthRangeMax: 2.0,
    materialComposition: 'Altın, gümüş, mücevher, taş',
    estimatedValue: 'Çok Yüksek (1000kg+ altın)',
    archaeologicalSignificance: 'Çok Yüksek',
    typicalAge: 'Ortaçağ (500-1500)',
    geographicDistribution: 'Şilk Yolu güzergahları'
  },
  'metal-mass': {
    id: 'metal-mass',
    type: 'metal-mass',
    name: 'Metal Yığını',
    description: 'Gömülü metal madenler ve yığınlar - Antik dönem maden işletmelerinin depo alanları',
    icon: '⚙️',
    category: 'storage',
    categoryName: STRUCTURE_CATEGORIES.storage.name,
    safetyRisk: 'low',
    excavationDifficulty: 'moderate',
    magneticSignature: '600-2000 nT',
    geometryType: 'Masif elipsoid',
    averageSize: '3-8m',
    detectionAccuracy: 89,
    depthRangeMin: 2.0,
    depthRangeMax: 8.0,
    materialComposition: 'Demir cevheri, bakır, kalay',
    estimatedValue: 'Yüksek (ticari)',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Tunç Çağı (3000-1200 M.Ö.)',
    geographicDistribution: 'Anadolu, Balkanlar, Ortadoğu'
  },
  'underground-room': {
    id: 'underground-room',
    type: 'underground-room',
    name: 'Yer Altı Odası',
    description: 'Yapılı yeraltı odaları ve odacıklar - Konut, depo ve kültsel amaçlı yeraltı yapıları',
    icon: '🏚️',
    category: 'utility',
    categoryName: STRUCTURE_CATEGORIES.utility.name,
    safetyRisk: 'high',
    excavationDifficulty: 'difficult',
    magneticSignature: '150-500 nT',
    geometryType: 'Dikdörtgen prizma',
    averageSize: '3-6m × 4-8m',
    detectionAccuracy: 85,
    depthRangeMin: 3.0,
    depthRangeMax: 12.0,
    materialComposition: 'Taş, tuğla, harç, ahşap',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Çok Yüksek',
    typicalAge: 'Kapadokya Saray Dönemi (1600-1200 M.Ö.)',
    geographicDistribution: 'Kapadokya, Malta, Kıbrıs'
  },
  'tunnel-line': {
    id: 'tunnel-line',
    type: 'tunnel-line',
    name: 'Tünel Hattı',
    description: 'Yeraltı tünel ağları ve geçiş yolları - Antik şehirler arasındaki gizli ve straejik bağlantılar',
    icon: '🌀',
    category: 'structural',
    categoryName: STRUCTURE_CATEGORIES.structural.name,
    safetyRisk: 'high',
    excavationDifficulty: 'very_difficult',
    magneticSignature: '100-400 nT',
    geometryType: 'Silindir/Dikdörtgen kanal',
    averageSize: '1.5-2.5m × 100m+',
    detectionAccuracy: 82,
    depthRangeMin: 5.0,
    depthRangeMax: 15.0,
    materialComposition: 'Taş yapıt',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Kritik',
    typicalAge: 'Ortaçağ (1000-1500)',
    geographicDistribution: 'Orta Doğu, Persia, Roma İmparatorluğu'
  },
  'void-anomaly': {
    id: 'void-anomaly',
    type: 'void-anomaly',
    name: 'Boşluk Anomalisi',
    description: 'Yapısız boşluklar ve madencilik izleri - Doğal mağaralar ve antik kazı işleri',
    icon: '⭐',
    category: 'structural',
    categoryName: STRUCTURE_CATEGORIES.structural.name,
    safetyRisk: 'high',
    excavationDifficulty: 'difficult',
    magneticSignature: '50-200 nT',
    geometryType: 'Düzensiz boşluk',
    averageSize: '2-15m',
    detectionAccuracy: 87,
    depthRangeMin: 3.0,
    depthRangeMax: 20.0,
    materialComposition: 'Hava boşluğu',
    estimatedValue: 'Jeolojik',
    archaeologicalSignificance: 'Orta',
    typicalAge: 'Holosen ve daha eski',
    geographicDistribution: 'Kireçtaşı bölgeleri'
  },
  'storage-room': {
    id: 'storage-room',
    type: 'storage-room',
    name: 'Depolama Odası',
    description: 'Ürün ve kaynak depolanan yeraltı odaları - Buğday, şarap, zeytinyağı ve hayvan balık depoları',
    icon: '🏺',
    category: 'storage',
    categoryName: STRUCTURE_CATEGORIES.storage.name,
    safetyRisk: 'medium',
    excavationDifficulty: 'moderate',
    magneticSignature: '100-400 nT',
    geometryType: 'Dikdörtgen odalar',
    averageSize: '4-10m × 3-6m',
    detectionAccuracy: 86,
    depthRangeMin: 2.0,
    depthRangeMax: 8.0,
    materialComposition: 'Tuğla, taş, harç, çömlekçilik ürünleri',
    estimatedValue: 'Orta (içerik)',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Roma Dönemi (100-500 M.S.)',
    geographicDistribution: 'Roma İmparatorluğu toprakları'
  },
  'sarcophagus': {
    id: 'sarcophagus',
    type: 'sarcophagus',
    name: 'Lahit',
    description: 'Antik lahitler ve cenaze odaları - Misrli, Numidyalı ve Roma nüfuzlu kültürlere ait',
    icon: '🪦',
    category: 'burial',
    categoryName: STRUCTURE_CATEGORIES.burial.name,
    safetyRisk: 'low',
    excavationDifficulty: 'moderate',
    magneticSignature: '250-700 nT',
    geometryType: 'Dikdörtgen antropomorf',
    averageSize: '2.0m × 0.8m × 0.8m',
    detectionAccuracy: 90,
    depthRangeMin: 1.0,
    depthRangeMax: 5.0,
    materialComposition: 'Granit, mermer, kireçtaşı',
    estimatedValue: 'Yüksek (arkeolojik)',
    archaeologicalSignificance: 'Kritik',
    typicalAge: 'Antik Dönem (500 M.Ö.-500 M.S.)',
    geographicDistribution: 'Misır, Nubia, Levant, Kuzey Afrika'
  },
  'ancient-room': {
    id: 'ancient-room',
    type: 'ancient-room',
    name: 'Antik Oda',
    description: 'Eski medeniyetlere ait yapılı odalar - Saray, kilise, sinagog ve konut yapıları',
    icon: '🏛️',
    category: 'utility',
    categoryName: STRUCTURE_CATEGORIES.utility.name,
    safetyRisk: 'medium',
    excavationDifficulty: 'moderate',
    magneticSignature: '150-500 nT',
    geometryType: 'Dikdörtgen/Kare',
    averageSize: '3-8m × 3-8m',
    detectionAccuracy: 88,
    depthRangeMin: 1.0,
    depthRangeMax: 6.0,
    materialComposition: 'Taş, tuğla, mermer, harç',
    estimatedValue: 'Yüksek (arkeolojik)',
    archaeologicalSignificance: 'Çok Yüksek',
    typicalAge: 'Antik Dönem (3000 M.Ö.-500 M.S.)',
    geographicDistribution: 'Akdeniz, Ortadoğu, Anadolu'
  },
  'stone-tomb': {
    id: 'stone-tomb',
    type: 'stone-tomb',
    name: 'Taş Mezar',
    description: 'Taş işçiliği ile yapılmış mezarlar - Kaya kesme ve taş yapı teknikleri',
    icon: '🪨',
    category: 'burial',
    categoryName: STRUCTURE_CATEGORIES.burial.name,
    safetyRisk: 'medium',
    excavationDifficulty: 'difficult',
    magneticSignature: '300-900 nT',
    geometryType: 'Şapel yapısı',
    averageSize: '2-4m × 2-3m',
    detectionAccuracy: 91,
    depthRangeMin: 2.0,
    depthRangeMax: 6.0,
    materialComposition: 'Granit, bazalt, kireçtaşı',
    estimatedValue: 'Yüksek (arkeolojik)',
    archaeologicalSignificance: 'Kritik',
    typicalAge: 'Neolitik-Antik (6000 M.Ö.-500 M.S.)',
    geographicDistribution: 'Megalit kültürleri'
  },
  'ancient-storage': {
    id: 'ancient-storage',
    type: 'ancient-storage',
    name: 'Antik Depo',
    description: 'Eski depolama yapıları ve ambarlar - Saray ve şehir yönetim merkezlerine ait ürün depoları',
    icon: '📚',
    category: 'storage',
    categoryName: STRUCTURE_CATEGORIES.storage.name,
    safetyRisk: 'low',
    excavationDifficulty: 'moderate',
    magneticSignature: '200-600 nT',
    geometryType: 'Dikdörtgen depoları',
    averageSize: '5-12m × 4-8m',
    detectionAccuracy: 87,
    depthRangeMin: 1.0,
    depthRangeMax: 5.0,
    materialComposition: 'Tuğla, taş, ahşap kirişler',
    estimatedValue: 'Orta (içerik)',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Bronze-Iron Çağı (3000-500 M.Ö.)',
    geographicDistribution: 'Minoan, Mycenae, Hitit'
  },
  'rectangular-form': {
    id: 'rectangular-form',
    type: 'rectangular-form',
    name: 'Dikdörtgen Yapı',
    description: 'Dikdörtgen şekilli yapı kalıntıları - Yapı temelleri ve yapı kalıntıları',
    icon: '▭',
    category: 'structural',
    categoryName: STRUCTURE_CATEGORIES.structural.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '100-400 nT',
    geometryType: 'Dikdörtgen',
    averageSize: '4-12m × 3-8m',
    detectionAccuracy: 84,
    depthRangeMin: 0.5,
    depthRangeMax: 3.0,
    materialComposition: 'Taş temel',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Orta',
    typicalAge: 'Holosen',
    geographicDistribution: 'Global'
  },
  'circular-room': {
    id: 'circular-room',
    type: 'circular-room',
    name: 'Dairesel Oda',
    description: 'Dairesel yapılı odalar ve kümeler - Ritüel alanları ve keşifname (dolmen) yapıları',
    icon: '●',
    category: 'structural',
    categoryName: STRUCTURE_CATEGORIES.structural.name,
    safetyRisk: 'low',
    excavationDifficulty: 'moderate',
    magneticSignature: '150-500 nT',
    geometryType: 'Dairesel/Oval',
    averageSize: '3-8m çapında',
    detectionAccuracy: 83,
    depthRangeMin: 0.5,
    depthRangeMax: 4.0,
    materialComposition: 'Taş, harç',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Neolitik-Antik (6000 M.Ö.-500 M.S.)',
    geographicDistribution: 'Megalit kültürleri'
  },
  'dense-cluster': {
    id: 'dense-cluster',
    type: 'dense-cluster',
    name: 'Yoğun Küme',
    description: 'Yoğun malzeme ve yapı kümesi - Seramik üretim merkezleri ve metalurji depoları',
    icon: '◆',
    category: 'structural',
    categoryName: STRUCTURE_CATEGORIES.structural.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '400-1200 nT',
    geometryType: 'Kümesel',
    averageSize: '2-6m',
    detectionAccuracy: 86,
    depthRangeMin: 0.3,
    depthRangeMax: 2.0,
    materialComposition: 'Seramik, metal, cüruf',
    estimatedValue: 'Orta',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Bronze-Iron Çağı',
    geographicDistribution: 'Antik ticaret merkezleri'
  },
  'gold-vault': {
    id: 'gold-vault',
    type: 'gold-vault',
    name: 'Altın Hazinesi',
    description: 'Altın ve değerli metal depoları - Saraylar ve hazine sistemleri tarafından gizlenen zenginlikler',
    icon: '🏆',
    category: 'storage',
    categoryName: STRUCTURE_CATEGORIES.storage.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '500-1500 nT',
    geometryType: 'Odacık yapısı',
    averageSize: '2-4m × 1.5-3m',
    detectionAccuracy: 94,
    depthRangeMin: 1.0,
    depthRangeMax: 4.0,
    materialComposition: 'Altın (%99), gümüş, alaşımlar',
    estimatedValue: 'Çok Yüksek (500kg+ altın)',
    archaeologicalSignificance: 'Çok Yüksek',
    typicalAge: 'Ortaçağ-Modern (1000-1900)',
    geographicDistribution: 'İmparyatorsonsus merkez şehirleri'
  },
  'coin-cache': {
    id: 'coin-cache',
    type: 'coin-cache',
    name: 'Madeni Para Deposu',
    description: 'Gömülü madeni paralar ve hazine - Tüccar, asker ve yöneticiler tarafından acil durum için gizlenmiş para',
    icon: '🪙',
    category: 'storage',
    categoryName: STRUCTURE_CATEGORIES.storage.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '200-800 nT',
    geometryType: 'Madeni para (numismatik)',
    averageSize: '0.2-0.5m',
    detectionAccuracy: 93,
    depthRangeMin: 0.3,
    depthRangeMax: 2.0,
    materialComposition: 'Altın, gümüş, bakır, bronz',
    estimatedValue: 'Yüksek (100-1000kg)',
    archaeologicalSignificance: 'Çok Yüksek',
    typicalAge: 'Antik-Modern (500 M.Ö.-1950)',
    geographicDistribution: 'Global ticaret ağları'
  },
  'pottery-cluster': {
    id: 'pottery-cluster',
    type: 'pottery-cluster',
    name: 'Seramik Kümesi',
    description: 'Antik seramikler ve çanak çömlek - Günlük yaşam eşyaları ve özel kullanım kapları',
    icon: '🏺',
    category: 'storage',
    categoryName: STRUCTURE_CATEGORIES.storage.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '50-300 nT',
    geometryType: 'Kümesel dağılım',
    averageSize: '1-3m',
    detectionAccuracy: 79,
    depthRangeMin: 0.2,
    depthRangeMax: 2.0,
    materialComposition: 'Seramik, kil, fırında pişmiş',
    estimatedValue: 'Orta (arkeolojik)',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Bronze-Antik Çağ (3000 M.Ö.-500 M.S.)',
    geographicDistribution: 'Akdeniz medeniyetleri'
  },
  'temple-foundation': {
    id: 'temple-foundation',
    type: 'temple-foundation',
    name: 'Tapınak Temeli',
    description: 'Antik tapınak temel kalıntıları - Dini ibadet merkez esas yapıları',
    icon: '🛕',
    category: 'sacred',
    categoryName: STRUCTURE_CATEGORIES.sacred.name,
    safetyRisk: 'medium',
    excavationDifficulty: 'difficult',
    magneticSignature: '200-800 nT',
    geometryType: 'Dikdörtgen/Kare platform',
    averageSize: '8-20m × 8-20m',
    detectionAccuracy: 89,
    depthRangeMin: 1.0,
    depthRangeMax: 5.0,
    materialComposition: 'Mermer, kireçtaşı, granit',
    estimatedValue: 'Kritik (arkeolojik)',
    archaeologicalSignificance: 'Kritik',
    typicalAge: 'Antik Dönem (1000 M.Ö.-500 M.S.)',
    geographicDistribution: 'Akdeniz tapınak kültü'
  },
  'fortress-wall': {
    id: 'fortress-wall',
    type: 'fortress-wall',
    name: 'Kale Duvarı',
    description: 'Kaleler ve savunma duvarları - Stratejik konumlarda inşa edilen koruma yapıları',
    icon: '🏰',
    category: 'defensive',
    categoryName: STRUCTURE_CATEGORIES.defensive.name,
    safetyRisk: 'high',
    excavationDifficulty: 'very_difficult',
    magneticSignature: '400-1500 nT',
    geometryType: 'Duvar yapısı',
    averageSize: '1.5-3m × 100m+',
    detectionAccuracy: 85,
    depthRangeMin: 1.0,
    depthRangeMax: 8.0,
    materialComposition: 'Taş, harç, ahşap pallisade',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Kritik',
    typicalAge: 'Bronze Çağ-Modern (2000 M.Ö.-1900)',
    geographicDistribution: 'Tüm kıtalı ülkeler'
  },
  'water-cistern': {
    id: 'water-cistern',
    type: 'water-cistern',
    name: 'Su Haznesi',
    description: 'Yeraltı su depolama sistemleri - Kurak dönemlerde su ihtiyacı karşılamak için antik su yönetimi',
    icon: '💧',
    category: 'utility',
    categoryName: STRUCTURE_CATEGORIES.utility.name,
    safetyRisk: 'high',
    excavationDifficulty: 'difficult',
    magneticSignature: '100-400 nT',
    geometryType: 'Dairesel/Oval hazneler',
    averageSize: '4-6m çapında',
    detectionAccuracy: 83,
    depthRangeMin: 3.0,
    depthRangeMax: 10.0,
    materialComposition: 'Taş, harç, kireç dönerme',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Orta',
    typicalAge: 'Antik-Ortaçağ (500 M.Ö.-1500)',
    geographicDistribution: 'Kurak iklim bölgeleri'
  },
  'burial-chamber': {
    id: 'burial-chamber',
    type: 'burial-chamber',
    name: 'Gömü Odası',
    description: 'Yer altı gömü ve mezar odaları - Bireysel ve toplu gömü alanları',
    icon: '⚱️',
    category: 'burial',
    categoryName: STRUCTURE_CATEGORIES.burial.name,
    safetyRisk: 'high',
    excavationDifficulty: 'difficult',
    magneticSignature: '200-700 nT',
    geometryType: 'Odacık yapısı',
    averageSize: '2-4m × 2-3m',
    detectionAccuracy: 88,
    depthRangeMin: 2.0,
    depthRangeMax: 6.0,
    materialComposition: 'Taş, tuğla, harç',
    estimatedValue: 'Çok Yüksek (arkeolojik)',
    archaeologicalSignificance: 'Kritik',
    typicalAge: 'Antik-Ortaçağ (1000 M.Ö.-1000)',
    geographicDistribution: 'Global'
  },
  'geometric-foundation': {
    id: 'geometric-foundation',
    type: 'geometric-foundation',
    name: 'Geometrik Temel',
    description: 'Geometrik düzende yapı temelleri - Matemtik ve geometri temelli inşaat dizaynı',
    icon: '◈',
    category: 'structural',
    categoryName: STRUCTURE_CATEGORIES.structural.name,
    safetyRisk: 'low',
    excavationDifficulty: 'moderate',
    magneticSignature: '150-500 nT',
    geometryType: 'Doktriner geometrik',
    averageSize: '5-15m × 5-15m',
    detectionAccuracy: 87,
    depthRangeMin: 0.5,
    depthRangeMax: 3.0,
    materialComposition: 'Taş, kil, harç',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Orta',
    typicalAge: 'Bronze-Antik (3000 M.Ö.-500 M.S.)',
    geographicDistribution: 'Mezopotamya, Mısır, Endüs'
  },
  'ventilation-shaft': {
    id: 'ventilation-shaft',
    type: 'ventilation-shaft',
    name: 'Havalandırma Şaftı',
    description: 'Yeraltı havalandırma ve bacalar - Yeraltı yapılarının havalandırması için sistem',
    icon: '🌬️',
    category: 'utility',
    categoryName: STRUCTURE_CATEGORIES.utility.name,
    safetyRisk: 'high',
    excavationDifficulty: 'difficult',
    magneticSignature: '50-250 nT',
    geometryType: 'Dikine şaft',
    averageSize: '0.5-1.5m çapında',
    detectionAccuracy: 81,
    depthRangeMin: 3.0,
    depthRangeMax: 20.0,
    materialComposition: 'Taş, tuğla',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Orta',
    typicalAge: 'Kapadokya Sarayları (1600-1200 M.Ö.)',
    geographicDistribution: 'Kapadokya, Misır'
  },
  'crystal-chamber': {
    id: 'crystal-chamber',
    type: 'crystal-chamber',
    name: 'Kristal Odası',
    description: 'Kristal ve maden oluşumları - Jeolojik maden birikintileri',
    icon: '💠',
    category: 'storage',
    categoryName: STRUCTURE_CATEGORIES.storage.name,
    safetyRisk: 'medium',
    excavationDifficulty: 'moderate',
    magneticSignature: '300-1000 nT',
    geometryType: 'Kristal formasyonları',
    averageSize: '2-8m',
    detectionAccuracy: 84,
    depthRangeMin: 1.0,
    depthRangeMax: 10.0,
    materialComposition: 'Kuarç, feldspat, mika',
    estimatedValue: 'Orta (jeolojik)',
    archaeologicalSignificance: 'Düşük',
    typicalAge: 'Prehistorik (>100000 yıl)',
    geographicDistribution: 'Tüm kıtalar'
  },
  'aqueduct-system': {
    id: 'aqueduct-system',
    type: 'aqueduct-system',
    name: 'Su Kanalı Sistemi',
    description: 'Antik su yönetimi sistemleri - Roma ve İslam medeniyetlerinin yüksek mühendislik başarıları',
    icon: '~',
    category: 'utility',
    categoryName: STRUCTURE_CATEGORIES.utility.name,
    safetyRisk: 'medium',
    excavationDifficulty: 'very_difficult',
    magneticSignature: '150-600 nT',
    geometryType: 'Kanal ağları',
    averageSize: '1-2m × 1000m+',
    detectionAccuracy: 80,
    depthRangeMin: 2.0,
    depthRangeMax: 15.0,
    materialComposition: 'Tuğla, taş, harç, kurşun',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Kritik',
    typicalAge: 'Roma-İslam (100-1500)',
    geographicDistribution: 'Roma İmparatorluğu, Persia'
  },
  'metallic-deposit': {
    id: 'metallic-deposit',
    type: 'metallic-deposit',
    name: 'Metal Yatağı',
    description: 'Doğal metal cevher yatakları - Jeolojik demir, bakır, kalay ve altın oluşumları',
    icon: '⛏️',
    category: 'storage',
    categoryName: STRUCTURE_CATEGORIES.storage.name,
    safetyRisk: 'low',
    excavationDifficulty: 'moderate',
    magneticSignature: '800-2500 nT',
    geometryType: 'Masif veya damarlar',
    averageSize: '3-20m',
    detectionAccuracy: 91,
    depthRangeMin: 1.0,
    depthRangeMax: 50.0,
    materialComposition: 'Magnetit, demir cevheri, malakit',
    estimatedValue: 'Yüksek (endüstriyel)',
    archaeologicalSignificance: 'Orta',
    typicalAge: 'Prekambrian-Holosen',
    geographicDistribution: 'Tüm madencililik alanları'
  },
  'excavation-gallery': {
    id: 'excavation-gallery',
    type: 'excavation-gallery',
    name: 'Kazı Galerisi',
    description: 'Madencilik kazı izleri ve galeriler - Antik madencilerin çıkardıkları galeri ağları',
    icon: '📍',
    category: 'structural',
    categoryName: STRUCTURE_CATEGORIES.structural.name,
    safetyRisk: 'high',
    excavationDifficulty: 'very_difficult',
    magneticSignature: '200-700 nT',
    geometryType: 'Galeriler/Tüneller',
    averageSize: '1-3m × 50m+',
    detectionAccuracy: 83,
    depthRangeMin: 3.0,
    depthRangeMax: 30.0,
    materialComposition: 'Taş kazıntı',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Bronze Çağ-Antik (2000 M.Ö.-500 M.S.)',
    geographicDistribution: 'Maden bölgeleri'
  },
  'sculptural-mass': {
    id: 'sculptural-mass',
    type: 'sculptural-mass',
    name: 'Heykelli Yapı',
    description: 'Heykeltraş sanatı ve baskın semboller - Dinsel ve kraliyet heykelcilik',
    icon: '🗿',
    category: 'sacred',
    categoryName: STRUCTURE_CATEGORIES.sacred.name,
    safetyRisk: 'low',
    excavationDifficulty: 'moderate',
    magneticSignature: '400-1200 nT',
    geometryType: 'Antropomorf/Animalier',
    averageSize: '2-10m',
    detectionAccuracy: 86,
    depthRangeMin: 0.5,
    depthRangeMax: 4.0,
    materialComposition: 'Granit, mermer, bazalt',
    estimatedValue: 'Çok Yüksek (arkeolojik)',
    archaeologicalSignificance: 'Kritik',
    typicalAge: 'Antik-Ortaçağ (2000 M.Ö.-1500)',
    geographicDistribution: 'Mısır, Doğu Asya, Easter Island'
  },
  'assembly-hall': {
    id: 'assembly-hall',
    type: 'assembly-hall',
    name: 'Toplanma Salonu',
    description: 'Antik toplantı ve güç merkezleri - Kraliyet ve sivil yönetim merkez yeri',
    icon: '⛪',
    category: 'sacred',
    categoryName: STRUCTURE_CATEGORIES.sacred.name,
    safetyRisk: 'medium',
    excavationDifficulty: 'difficult',
    magneticSignature: '200-700 nT',
    geometryType: 'Büyük salon',
    averageSize: '10-30m × 10-20m',
    detectionAccuracy: 87,
    depthRangeMin: 1.0,
    depthRangeMax: 5.0,
    materialComposition: 'Taş, mermer, ahşap kolon',
    estimatedValue: 'Çok Yüksek (arkeolojik)',
    archaeologicalSignificance: 'Kritik',
    typicalAge: 'Antik-Ortaçağ (1000 M.Ö.-1500)',
    geographicDistribution: 'Medeniyetler merkezleri'
  },
  'treasure-vault': {
    id: 'treasure-vault',
    type: 'treasure-vault',
    name: 'Hazine Kasası',
    description: 'İmparatorluk hazinesi ve saklı deposu - Saray hazine odaları ve kraliyet hazineleri',
    icon: '🗝️',
    category: 'storage',
    categoryName: STRUCTURE_CATEGORIES.storage.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '600-1800 nT',
    geometryType: 'Kasa odacık',
    averageSize: '2-5m × 1.5-3m',
    detectionAccuracy: 96,
    depthRangeMin: 1.0,
    depthRangeMax: 4.0,
    materialComposition: 'Altın, gümüş, taş, ahşap',
    estimatedValue: 'Çok Yüksek (1000kg+ altın)',
    archaeologicalSignificance: 'Çok Yüksek',
    typicalAge: 'Ortaçağ-Modern (1000-1900)',
    geographicDistribution: 'İmparatorluk merkez şehirleri'
  },
  'mine-shaft': {
    id: 'mine-shaft',
    type: 'mine-shaft',
    name: 'Maden Şaftı',
    description: 'Antik maden işletme şaftları - Tazı, bakır, kalay ve gümüş madenciliği',
    icon: '🛤️',
    category: 'utility',
    categoryName: STRUCTURE_CATEGORIES.utility.name,
    safetyRisk: 'high',
    excavationDifficulty: 'very_difficult',
    magneticSignature: '500-1800 nT',
    geometryType: 'Dikine/Eğimli şaft',
    averageSize: '1-3m × 50-200m',
    detectionAccuracy: 82,
    depthRangeMin: 5.0,
    depthRangeMax: 100.0,
    materialComposition: 'Taş, cüruf, metal izi',
    estimatedValue: 'Orta (arkeolojik)',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Bronze-Antik (2000 M.Ö.-500 M.S.)',
    geographicDistribution: 'Maden zengin bölgeler'
  },
  'underground-garden': {
    id: 'underground-garden',
    type: 'underground-garden',
    name: 'Yeraltı Bahçesi',
    description: 'Dönemin gelişmiş tarım sistemleri - Kapalı ve kontrollü tarım alanları',
    icon: '🌿',
    category: 'utility',
    categoryName: STRUCTURE_CATEGORIES.utility.name,
    safetyRisk: 'low',
    excavationDifficulty: 'moderate',
    magneticSignature: '100-400 nT',
    geometryType: 'Terased bahçeler',
    averageSize: '5-20m × 5-20m',
    detectionAccuracy: 80,
    depthRangeMin: 1.0,
    depthRangeMax: 6.0,
    materialComposition: 'Taş, toprak, sulama kanalları',
    estimatedValue: 'Orta (arkeolojik)',
    archaeologicalSignificance: 'Orta',
    typicalAge: 'İslam Dönemi (700-1500)',
    geographicDistribution: 'Kurak iklim bölgeleri'
  },
  'divine-sanctuary': {
    id: 'divine-sanctuary',
    type: 'divine-sanctuary',
    name: 'İlahi Heykeli',
    description: 'Dini ritüeller için gizli salanlar - Gizli ibadet ve mistik ritüeller mekanı',
    icon: '✝️',
    category: 'sacred',
    categoryName: STRUCTURE_CATEGORIES.sacred.name,
    safetyRisk: 'medium',
    excavationDifficulty: 'difficult',
    magneticSignature: '300-900 nT',
    geometryType: 'İç mekân şapel',
    averageSize: '3-8m × 3-8m',
    detectionAccuracy: 88,
    depthRangeMin: 2.0,
    depthRangeMax: 8.0,
    materialComposition: 'Taş, mermer, dini sanat',
    estimatedValue: 'Çok Yüksek (arkeolojik)',
    archaeologicalSignificance: 'Kritik',
    typicalAge: 'Antik-Ortaçağ (100-1500)',
    geographicDistribution: 'Dini merkezler'
  },
  'cylindrical-tower': {
    id: 'cylindrical-tower',
    type: 'cylindrical-tower',
    name: 'Silindir Kule',
    description: 'Silindir şekilli savunma kuleleri - Hileli kale ve savunma kulesi',
    icon: '🗼',
    category: 'defensive',
    categoryName: STRUCTURE_CATEGORIES.defensive.name,
    safetyRisk: 'high',
    excavationDifficulty: 'very_difficult',
    magneticSignature: '500-1500 nT',
    geometryType: 'Silindir / Konik',
    averageSize: '5-15m çapında × 10-30m',
    detectionAccuracy: 85,
    depthRangeMin: 1.0,
    depthRangeMax: 8.0,
    materialComposition: 'Taş, tuğla, harç',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Bronze Çağ-Modern (2000 M.Ö.-1900)',
    geographicDistribution: 'Stratejik konumlar'
  },
  'ceremonial-pit': {
    id: 'ceremonial-pit',
    type: 'ceremonial-pit',
    name: 'Seremonyal Çukuru',
    description: 'Ritüel ve merasim alanları - Kurban ve dini merasimleri için çukurlar',
    icon: '🔮',
    category: 'sacred',
    categoryName: STRUCTURE_CATEGORIES.sacred.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '200-600 nT',
    geometryType: 'Dairesel/Oval çukur',
    averageSize: '2-5m çapında × 1-3m derin',
    detectionAccuracy: 82,
    depthRangeMin: 0.5,
    depthRangeMax: 3.0,
    materialComposition: 'Toprak, kemik, seramik',
    estimatedValue: 'Yüksek (arkeolojik)',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Neolitik-Antik (6000 M.Ö.-500 M.S.)',
    geographicDistribution: 'Dini merkezler'
  },
  'library-chamber': {
    id: 'library-chamber',
    type: 'library-chamber',
    name: 'Kütüphane Odası',
    description: 'Antik bilgi depo ve kütüphaneler - Tamamında yazıtlı kaynaklar saklanır',
    icon: '📖',
    category: 'storage',
    categoryName: STRUCTURE_CATEGORIES.storage.name,
    safetyRisk: 'low',
    excavationDifficulty: 'moderate',
    magneticSignature: '150-500 nT',
    geometryType: 'Odalı yapı',
    averageSize: '5-15m × 4-10m',
    detectionAccuracy: 85,
    depthRangeMin: 1.0,
    depthRangeMax: 5.0,
    materialComposition: 'Taş, mermer, ahşap',
    estimatedValue: 'Kritik (arkeolojik)',
    archaeologicalSignificance: 'Kritik',
    typicalAge: 'Antik-İslam (500 M.Ö.-1500)',
    geographicDistribution: 'Bilimsel merkezler'
  },
  'armory-vault': {
    id: 'armory-vault',
    type: 'armory-vault',
    name: 'Silah Deposu',
    description: 'Silah ve askeri teçhizat depoları - Ordu silah depolama ve lojistik merkezleri',
    icon: '⚔️',
    category: 'defensive',
    categoryName: STRUCTURE_CATEGORIES.defensive.name,
    safetyRisk: 'low',
    excavationDifficulty: 'moderate',
    magneticSignature: '700-2000 nT',
    geometryType: 'Depo odaları',
    averageSize: '5-10m × 4-8m',
    detectionAccuracy: 88,
    depthRangeMin: 1.0,
    depthRangeMax: 4.0,
    materialComposition: 'Demir, bakır, deri, ahşap',
    estimatedValue: 'Yüksek (arkeolojik)',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Antik-Ortaçağ (500 M.Ö.-1500)',
    geographicDistribution: 'Asker kaleleri'
  },
  'workshop-complex': {
    id: 'workshop-complex',
    type: 'workshop-complex',
    name: 'Atölye Kompleksi',
    description: 'Zanaat ve üretim merkezleri - Seramik, metal ve dokuma üretim alanları',
    icon: '🔨',
    category: 'utility',
    categoryName: STRUCTURE_CATEGORIES.utility.name,
    safetyRisk: 'low',
    excavationDifficulty: 'moderate',
    magneticSignature: '300-900 nT',
    geometryType: 'Birden fazla oda',
    averageSize: '8-20m × 6-15m',
    detectionAccuracy: 84,
    depthRangeMin: 0.5,
    depthRangeMax: 3.0,
    materialComposition: 'Tuğla, taş, ahşap, cüruf',
    estimatedValue: 'Yüksek (arkeolojik)',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Bronze-Antik (2000 M.Ö.-500 M.S.)',
    geographicDistribution: 'Ticaret merkez şehirleri'
  },
  wall: {
    id: 'wall',
    type: 'wall',
    name: 'Duvar',
    description: 'Bölme veya destek duvarı tespiti - Yapı kalıntıları arasındaki taş duvarlar',
    icon: '🧱',
    category: 'structural',
    categoryName: STRUCTURE_CATEGORIES.structural.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '100-500 nT',
    geometryType: 'Doğrusal duvar',
    averageSize: '0.5-1.5m × 10-50m',
    detectionAccuracy: 80,
    depthRangeMin: 0.3,
    depthRangeMax: 3.0,
    materialComposition: 'Taş, harç',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Orta',
    typicalAge: 'Holosen',
    geographicDistribution: 'Global'
  },
  pillar: {
    id: 'pillar',
    type: 'pillar',
    name: 'Sütun/Direk',
    description: 'Taşıyıcı yapı elemanı veya sütun - Yapı destekleme ve taşıyıcı sistemler',
    icon: '📐',
    category: 'structural',
    categoryName: STRUCTURE_CATEGORIES.structural.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '200-700 nT',
    geometryType: 'Silindir/Kare sütun',
    averageSize: '0.5-2m × 3-10m',
    detectionAccuracy: 82,
    depthRangeMin: 0.5,
    depthRangeMax: 3.0,
    materialComposition: 'Taş, mermer, granit',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Orta',
    typicalAge: 'Antik (500 M.Ö.-500 M.S.)',
    geographicDistribution: 'Yapı sahaları'
  },
  passage: {
    id: 'passage',
    type: 'passage',
    name: 'Geçit',
    description: 'İki alan arasındaki dar bağlantı yolu - Yapı bölümleri arasındaki geçiş alanları',
    icon: '🚪',
    category: 'structural',
    categoryName: STRUCTURE_CATEGORIES.structural.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '50-300 nT',
    geometryType: 'Dikdörtgen kanal',
    averageSize: '1-2m × 20-50m',
    detectionAccuracy: 78,
    depthRangeMin: 0.5,
    depthRangeMax: 3.0,
    materialComposition: 'Taş, tuğla',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Orta',
    typicalAge: 'Antik-Ortaçağ',
    geographicDistribution: 'Kompleks yapılar'
  },
  vault: {
    id: 'vault',
    type: 'vault',
    name: 'Mahzen/Kemer',
    description: 'Yeraltı saklama alanı veya kemerli yapı - Kemerli yapılar ve yeraltı depoları',
    icon: '🏦',
    category: 'storage',
    categoryName: STRUCTURE_CATEGORIES.storage.name,
    safetyRisk: 'medium',
    excavationDifficulty: 'moderate',
    magneticSignature: '200-700 nT',
    geometryType: 'Kemerli yapı',
    averageSize: '3-10m × 3-10m',
    detectionAccuracy: 86,
    depthRangeMin: 2.0,
    depthRangeMax: 8.0,
    materialComposition: 'Taş, tuğla, harç',
    estimatedValue: 'Yüksek (arkeolojik)',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Roma-İslam (100-1500)',
    geographicDistribution: 'İmparatorluk yapıları'
  },
  room: {
    id: 'room',
    type: 'room',
    name: 'Oda',
    description: 'Belirgin sınırları olan kapalı alan - Konut, ticari ve dini bina odaları',
    icon: '📦',
    category: 'utility',
    categoryName: STRUCTURE_CATEGORIES.utility.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '100-400 nT',
    geometryType: 'Dikdörtgen/Kare',
    averageSize: '3-8m × 3-8m',
    detectionAccuracy: 81,
    depthRangeMin: 0.5,
    depthRangeMax: 3.0,
    materialComposition: 'Taş, tuğla, toprak',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Orta',
    typicalAge: 'Holosen',
    geographicDistribution: 'Global'
  },
  staircase: {
    id: 'staircase',
    type: 'staircase',
    name: 'Merdiven',
    description: 'Katlar arası geçiş sağlayan yapı - Taş ve tuğla yapımı merdivenler',
    icon: '🪜',
    category: 'structural',
    categoryName: STRUCTURE_CATEGORIES.structural.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '150-600 nT',
    geometryType: 'Spirel/Doğrusal',
    averageSize: '1.5-3m × 3-10m',
    detectionAccuracy: 83,
    depthRangeMin: 0.5,
    depthRangeMax: 4.0,
    materialComposition: 'Taş, tuğla',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Orta',
    typicalAge: 'Antik-Modern',
    geographicDistribution: 'Çok katlı yapılar'
  },
  foundation: {
    id: 'foundation',
    type: 'foundation',
    name: 'Temel',
    description: 'Yapı tabanı ve temel taşları - Yapı üst yapısı destekleyen temel sistemleri',
    icon: '🏗️',
    category: 'structural',
    categoryName: STRUCTURE_CATEGORIES.structural.name,
    safetyRisk: 'low',
    excavationDifficulty: 'moderate',
    magneticSignature: '200-700 nT',
    geometryType: 'Temel duvarları',
    averageSize: '0.8-2m × değişken',
    detectionAccuracy: 85,
    depthRangeMin: 0.5,
    depthRangeMax: 2.5,
    materialComposition: 'Taş, tuğla, harç',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Orta',
    typicalAge: 'Holosen',
    geographicDistribution: 'Global'
  },
  tomb: {
    id: 'tomb',
    type: 'tomb',
    name: 'Mezar/Lahit',
    description: 'Tarihsel gömü veya mezar odası - Bireysel ve toplu gömü yerleri',
    icon: '⛩️',
    category: 'burial',
    categoryName: STRUCTURE_CATEGORIES.burial.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '250-800 nT',
    geometryType: 'Mezar şapeli',
    averageSize: '1.5-3m × 1.5-3m',
    detectionAccuracy: 89,
    depthRangeMin: 0.5,
    depthRangeMax: 3.0,
    materialComposition: 'Taş, mermer',
    estimatedValue: 'Yüksek (arkeolojik)',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Neolitik-Antik',
    geographicDistribution: 'Global'
  },
  tunnel: {
    id: 'tunnel',
    type: 'tunnel',
    name: 'Tünel',
    description: 'Yeraltı geçiş kanalı - Ulaştırma, sulama ve stratejik amaçlar için tüneller',
    icon: '🕳️',
    category: 'structural',
    categoryName: STRUCTURE_CATEGORIES.structural.name,
    safetyRisk: 'high',
    excavationDifficulty: 'very_difficult',
    magneticSignature: '150-600 nT',
    geometryType: 'Kanal tünel',
    averageSize: '1.5-3m × 50-500m',
    detectionAccuracy: 80,
    depthRangeMin: 2.0,
    depthRangeMax: 15.0,
    materialComposition: 'Taş, tuğla, harç',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Antik-Ortaçağ',
    geographicDistribution: 'Stratejik bölgeler'
  },
  column: {
    id: 'column',
    type: 'column',
    name: 'Kolon',
    description: 'Dikine taşıyıcı eleman - Yapı destek sistemleri ve dekoratif kolonlar',
    icon: '⛕',
    category: 'structural',
    categoryName: STRUCTURE_CATEGORIES.structural.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '300-900 nT',
    geometryType: 'Silindir sütun',
    averageSize: '1-3m × 5-15m',
    detectionAccuracy: 84,
    depthRangeMin: 0.5,
    depthRangeMax: 3.0,
    materialComposition: 'Mermer, granit, taş',
    estimatedValue: 'Yüksek (arkeolojik)',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Antik (500 M.Ö.-500 M.S.)',
    geographicDistribution: 'Antik tapınak ve saraylar'
  },
  entrance: {
    id: 'entrance',
    type: 'entrance',
    name: 'Giriş/Kapı',
    description: 'Yapı giriş noktası - Ana ve yan kapılar ve giriş portalleri',
    icon: '🚪',
    category: 'defensive',
    categoryName: STRUCTURE_CATEGORIES.defensive.name,
    safetyRisk: 'low',
    excavationDifficulty: 'easy',
    magneticSignature: '100-500 nT',
    geometryType: 'Portal/Kapı çerçevesi',
    averageSize: '1.5-3m × 2-5m',
    detectionAccuracy: 81,
    depthRangeMin: 0.3,
    depthRangeMax: 2.0,
    materialComposition: 'Taş, harç',
    estimatedValue: 'Arkeolojik',
    archaeologicalSignificance: 'Orta',
    typicalAge: 'Holosen',
    geographicDistribution: 'Global'
  },
  gate: {
    id: 'gate',
    type: 'gate',
    name: 'Ana Kapı',
    description: 'Büyük ölçekli giriş kapısı - Şehir kapıları ve kale ana girişleri',
    icon: '⛩️',
    category: 'defensive',
    categoryName: STRUCTURE_CATEGORIES.defensive.name,
    safetyRisk: 'low',
    excavationDifficulty: 'moderate',
    magneticSignature: '300-1200 nT',
    geometryType: 'Kapı kuleleri',
    averageSize: '3-8m × 3-8m',
    detectionAccuracy: 86,
    depthRangeMin: 0.5,
    depthRangeMax: 3.0,
    materialComposition: 'Taş, tuğla, metal',
    estimatedValue: 'Yüksek (arkeolojik)',
    archaeologicalSignificance: 'Yüksek',
    typicalAge: 'Antik-Ortaçağ',
    geographicDistribution: 'Şehir ve kale'
  }
};

// Post-process all structures to add commonMaterials from materialComposition
Object.values(STRUCTURES).forEach((structure) => {
  if (!structure.commonMaterials && structure.materialComposition) {
    structure.commonMaterials = parseMaterials(structure.materialComposition);
  }
});

// Export function to get all structures as array
export const getAllStructures = (): StructureDefinition[] => {
  return Object.values(STRUCTURES);
};
